import type { Metadata } from "next";
import { Zen_Maru_Gothic } from "next/font/google";
import { ThemeProvider } from "next-themes";

import Layout from "@/components/Layout";

import "./globals.scss";

const zenMaruGothic = Zen_Maru_Gothic({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp" suppressHydrationWarning>
      <body className={zenMaruGothic.className}>
        <ThemeProvider enableSystem={true}>
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
